### ISSUE TITLE
Jcasc config does not support reduceMotion, maxColumns or textscale

### ISSUE THREAD

**Issue by nvp152** [jenkinsci/build-monitor-plugin#798]
### What feature do you want to see added?

Currently when using jcasc and yaml i can do this
```
    views:
    - buildMonitor:
        name: "My Radiator"
        config:
          displayBadgesFrom: "getLastBuild"
          order: "byFullName"
          #reduceMotion: true
          #maxColumns: 2
          #textScale: 1.5
        jobNames:
        - "job1"
        - "job2"
```
However none of reduceMotion, maxColumns or textscale are supported. It would be great if those could be added as well.
